"""add viewed_tutorial to users

Revision ID: 9cf370b7be08
Revises: d9c2dea1b1b8
Create Date: 2025-12-02 19:47:24.832201

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9cf370b7be08"
down_revision: Union[str, None] = "d9c2dea1b1b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "viewed_tutorial", sa.Boolean(), nullable=False, server_default="false"
        ),
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "viewed_tutorial", schema="app")
    # ### end Alembic commands ###
