"""initial_schema_from_models

Revision ID: 0fd077a09577
Revises: 
Create Date: 2025-08-28 16:02:19.002039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column
# revision identifiers, used by Alembic.
revision: str = '0fd077a09577'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure the app schema exists
    op.execute("CREATE SCHEMA IF NOT EXISTS app")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='app'
    )
    op.create_index(op.f('ix_app_permissions_id'), 'permissions', ['id'], unique=False, schema='app')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='app'
    )
    op.create_index(op.f('ix_app_roles_id'), 'roles', ['id'], unique=False, schema='app')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_users_metadata', 'users', ['user_metadata'], unique=False, schema='app', postgresql_using='gin')
    op.create_index(op.f('ix_app_users_email'), 'users', ['email'], unique=True, schema='app')
    op.create_index(op.f('ix_app_users_id'), 'users', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_users_username'), 'users', ['username'], unique=True, schema='app')
    op.create_table('document_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=True),
    sa.Column('text_direction', sa.String(length=50), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('hierarchy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collection_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['app.users.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['app.users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_document_collections_created_by', 'document_collections', ['created_by_id'], unique=False, schema='app')
    op.create_index('idx_document_collections_hierarchy', 'document_collections', ['hierarchy'], unique=False, schema='app', postgresql_using='gin')
    op.create_index('idx_document_collections_metadata', 'document_collections', ['collection_metadata'], unique=False, schema='app', postgresql_using='gin')
    op.create_index('idx_document_collections_modified_by', 'document_collections', ['modified_by_id'], unique=False, schema='app')
    op.create_index('idx_document_collections_owner', 'document_collections', ['owner_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_document_collections_id'), 'document_collections', ['id'], unique=False, schema='app')
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_groups_id'), 'groups', ['id'], unique=False, schema='app')
    op.create_table('object_sharing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('shared_with_id', sa.Integer(), nullable=True),
    sa.Column('shared_with_type', sa.String(length=10), nullable=True),
    sa.Column('access_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_object_sharing_object', 'object_sharing', ['object_id', 'object_type'], unique=False, schema='app')
    op.create_index('idx_object_sharing_shared_with', 'object_sharing', ['shared_with_id', 'shared_with_type'], unique=False, schema='app')
    op.create_index(op.f('ix_app_object_sharing_id'), 'object_sharing', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_object_sharing_object_id'), 'object_sharing', ['object_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_object_sharing_object_type'), 'object_sharing', ['object_type'], unique=False, schema='app')
    op.create_index(op.f('ix_app_object_sharing_shared_with_id'), 'object_sharing', ['shared_with_id'], unique=False, schema='app')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['app.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['app.roles.id'], ),
    schema='app'
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_title', sa.String(length=50), nullable=False),
    sa.Column('site_logo_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_site_settings_updated_by', 'site_settings', ['updated_by_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_site_settings_id'), 'site_settings', ['id'], unique=False, schema='app')
    op.create_table('user_passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='app'
    )
    op.create_index('idx_user_passwords_user_id', 'user_passwords', ['user_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_user_passwords_id'), 'user_passwords', ['id'], unique=False, schema='app')
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['app.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    schema='app'
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_collection_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_collection_id'], ['app.document_collections.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_documents_collection_id', 'documents', ['document_collection_id'], unique=False, schema='app')
    op.create_index('idx_documents_owner', 'documents', ['owner_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_documents_id'), 'documents', ['id'], unique=False, schema='app')
    op.create_table('group_members',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['app.groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    schema='app'
    )
    op.create_table('document_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('hierarchy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['app.documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_document_elements_content', 'document_elements', ['content'], unique=False, schema='app', postgresql_using='gin')
    op.create_index('idx_document_elements_document_id', 'document_elements', ['document_id'], unique=False, schema='app')
    op.create_index('idx_document_elements_hierarchy', 'document_elements', ['hierarchy'], unique=False, schema='app', postgresql_using='gin')
    op.create_index(op.f('ix_app_document_elements_id'), 'document_elements', ['id'], unique=False, schema='app')
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_collection_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('document_element_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('generator', sa.String(length=255), nullable=True),
    sa.Column('generated', sa.DateTime(), nullable=True),
    sa.Column('motivation', sa.String(length=100), nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('annotation_type', sa.String(length=100), nullable=True),
    sa.Column('context', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['app.users.id'], ),
    sa.ForeignKeyConstraint(['document_collection_id'], ['app.document_collections.id'], ),
    sa.ForeignKeyConstraint(['document_element_id'], ['app.document_elements.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['app.documents.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_annotations_body', 'annotations', ['body'], unique=False, schema='app', postgresql_using='gin')
    op.create_index('idx_annotations_collection_id', 'annotations', ['document_collection_id'], unique=False, schema='app')
    op.create_index('idx_annotations_created', 'annotations', ['created'], unique=False, schema='app')
    op.create_index('idx_annotations_creator_id', 'annotations', ['creator_id'], unique=False, schema='app')
    op.create_index('idx_annotations_document_element_id', 'annotations', ['document_element_id'], unique=False, schema='app')
    op.create_index('idx_annotations_document_id', 'annotations', ['document_id'], unique=False, schema='app')
    op.create_index('idx_annotations_motivation', 'annotations', ['motivation'], unique=False, schema='app')
    op.create_index('idx_annotations_owner_id', 'annotations', ['owner_id'], unique=False, schema='app')
    op.create_index('idx_annotations_target', 'annotations', ['target'], unique=False, schema='app', postgresql_using='gin')
    op.create_index('idx_annotations_type', 'annotations', ['type'], unique=False, schema='app')
    op.create_index(op.f('ix_app_annotations_id'), 'annotations', ['id'], unique=False, schema='app')

    roles_table = table('roles',
        column('name', sa.String),
        column('description', sa.String),
        schema='app'
    )
    
    permissions_table = table('permissions',
        column('name', sa.String),
        column('description', sa.String),
        schema='app'
    )

    role_permissions_table = table('role_permissions',
        column('role_id', sa.Integer),
        column('permission_id', sa.Integer),
        schema='app'
    )
    
    permissions_data = [
        {'name': 'create_document_collection', 'description': 'Create document collections'},
        {'name': 'create_document', 'description': 'Create documents'},
        {'name': 'create_document_element', 'description': 'Create document elements'},
        {'name': 'create_scholarly_annotation', 'description': 'Create scholarly annotations'},
        {'name': 'create_commenting_annotation', 'description': 'Create commenting annotations'},
        {'name': 'comment_on_scholarly_annotation', 'description': 'Comment on scholarly annotations'},
        {'name': 'comment_on_commenting_annotation', 'description': 'Comment on commenting annotations'},
        {'name': 'access_admin_dashboard', 'description': 'Access administrative dashboard'},
        {'name': 'manage_users', 'description': 'Manage user accounts'},
        {'name': 'manage_roles', 'description': 'Assign and remove user roles'},
        {'name': 'edit_any_content', 'description': 'Edit any content in the system'},
        {'name': 'delete_any_content', 'description': 'Delete any content in the system'},
        {'name': 'view_all_content', 'description': 'View all content for oversight'},
        {'name': 'create_group', 'description': 'Create groups/classrooms'},
    ]
    
    op.bulk_insert(permissions_table, permissions_data)
    
    # Insert roles
    roles_data = [
        {'name': 'admin', 'description': 'Full system administrator'},
        {'name': 'verified_scholar', 'description': 'Verified scholar with scholarly annotation privileges'},
        {'name': 'general_user', 'description': 'General user with basic annotation capabilities'},
    ]
    
    op.bulk_insert(roles_table, roles_data)
        # Get connection to fetch IDs for role-permission mappings
    connection = op.get_bind()
    
    # Fetch role IDs
    admin_role_id = connection.execute(
        sa.text("SELECT id FROM app.roles WHERE name = 'admin'")
    ).fetchone()[0]
    
    scholar_role_id = connection.execute(
        sa.text("SELECT id FROM app.roles WHERE name = 'verified_scholar'")
    ).fetchone()[0]
    
    user_role_id = connection.execute(
        sa.text("SELECT id FROM app.roles WHERE name = 'general_user'")
    ).fetchone()[0]
    
    # Fetch permission IDs
    perm_ids = {}
    for perm in permissions_data:
        result = connection.execute(
            sa.text(f"SELECT id FROM app.permissions WHERE name = '{perm['name']}'")
        ).fetchone()
        perm_ids[perm['name']] = result[0]
    
    # Create role-permission mappings
    role_permission_mappings = []
    
    # Admin gets all permissions
    for perm_id in perm_ids.values():
        role_permission_mappings.append({'role_id': admin_role_id, 'permission_id': perm_id})
    
    # Verified Scholar permissions
    scholar_permissions = [
        'create_scholarly_annotation',
        'create_commenting_annotation', 
        'comment_on_scholarly_annotation',
        'comment_on_commenting_annotation'
    ]
    for perm_name in scholar_permissions:
        role_permission_mappings.append({
            'role_id': scholar_role_id, 
            'permission_id': perm_ids[perm_name]
        })
    
    # General User permissions
    user_permissions = [
        'create_commenting_annotation',
        'comment_on_commenting_annotation'
    ]
    for perm_name in user_permissions:
        role_permission_mappings.append({
            'role_id': user_role_id, 
            'permission_id': perm_ids[perm_name]
        })
    
    op.bulk_insert(role_permissions_table, role_permission_mappings)
    ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_annotations_id'), table_name='annotations', schema='app')
    op.drop_index('idx_annotations_type', table_name='annotations', schema='app')
    op.drop_index('idx_annotations_target', table_name='annotations', schema='app', postgresql_using='gin')
    op.drop_index('idx_annotations_owner_id', table_name='annotations', schema='app')
    op.drop_index('idx_annotations_motivation', table_name='annotations', schema='app')
    op.drop_index('idx_annotations_document_id', table_name='annotations', schema='app')
    op.drop_index('idx_annotations_document_element_id', table_name='annotations', schema='app')
    op.drop_index('idx_annotations_creator_id', table_name='annotations', schema='app')
    op.drop_index('idx_annotations_created', table_name='annotations', schema='app')
    op.drop_index('idx_annotations_collection_id', table_name='annotations', schema='app')
    op.drop_index('idx_annotations_body', table_name='annotations', schema='app', postgresql_using='gin')
    op.drop_table('annotations', schema='app')
    op.drop_index(op.f('ix_app_document_elements_id'), table_name='document_elements', schema='app')
    op.drop_index('idx_document_elements_hierarchy', table_name='document_elements', schema='app', postgresql_using='gin')
    op.drop_index('idx_document_elements_document_id', table_name='document_elements', schema='app')
    op.drop_index('idx_document_elements_content', table_name='document_elements', schema='app', postgresql_using='gin')
    op.drop_table('document_elements', schema='app')
    op.drop_table('group_members', schema='app')
    op.drop_index(op.f('ix_app_documents_id'), table_name='documents', schema='app')
    op.drop_index('idx_documents_owner', table_name='documents', schema='app')
    op.drop_index('idx_documents_collection_id', table_name='documents', schema='app')
    op.drop_table('documents', schema='app')
    op.drop_table('user_roles', schema='app')
    op.drop_index(op.f('ix_app_user_passwords_id'), table_name='user_passwords', schema='app')
    op.drop_index('idx_user_passwords_user_id', table_name='user_passwords', schema='app')
    op.drop_table('user_passwords', schema='app')
    op.drop_index(op.f('ix_app_site_settings_id'), table_name='site_settings', schema='app')
    op.drop_index('idx_site_settings_updated_by', table_name='site_settings', schema='app')
    op.drop_table('site_settings', schema='app')
    op.drop_table('role_permissions', schema='app')
    op.drop_index(op.f('ix_app_object_sharing_shared_with_id'), table_name='object_sharing', schema='app')
    op.drop_index(op.f('ix_app_object_sharing_object_type'), table_name='object_sharing', schema='app')
    op.drop_index(op.f('ix_app_object_sharing_object_id'), table_name='object_sharing', schema='app')
    op.drop_index(op.f('ix_app_object_sharing_id'), table_name='object_sharing', schema='app')
    op.drop_index('idx_object_sharing_shared_with', table_name='object_sharing', schema='app')
    op.drop_index('idx_object_sharing_object', table_name='object_sharing', schema='app')
    op.drop_table('object_sharing', schema='app')
    op.drop_index(op.f('ix_app_groups_id'), table_name='groups', schema='app')
    op.drop_table('groups', schema='app')
    op.drop_index(op.f('ix_app_document_collections_id'), table_name='document_collections', schema='app')
    op.drop_index('idx_document_collections_owner', table_name='document_collections', schema='app')
    op.drop_index('idx_document_collections_modified_by', table_name='document_collections', schema='app')
    op.drop_index('idx_document_collections_metadata', table_name='document_collections', schema='app', postgresql_using='gin')
    op.drop_index('idx_document_collections_hierarchy', table_name='document_collections', schema='app', postgresql_using='gin')
    op.drop_index('idx_document_collections_created_by', table_name='document_collections', schema='app')
    op.drop_table('document_collections', schema='app')
    op.drop_index(op.f('ix_app_users_username'), table_name='users', schema='app')
    op.drop_index(op.f('ix_app_users_id'), table_name='users', schema='app')
    op.drop_index(op.f('ix_app_users_email'), table_name='users', schema='app')
    op.drop_index('idx_users_metadata', table_name='users', schema='app', postgresql_using='gin')
    op.drop_table('users', schema='app')
    op.drop_index(op.f('ix_app_roles_id'), table_name='roles', schema='app')
    op.drop_table('roles', schema='app')
    op.drop_index(op.f('ix_app_permissions_id'), table_name='permissions', schema='app')
    op.drop_table('permissions', schema='app')
    # ### end Alembic commands ###
