"""Initial migration

Revision ID: c2e2ba380e53
Revises: 
Create Date: 2025-06-02 15:26:13.156350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2e2ba380e53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_document_elements_content'), table_name='document_elements', schema='preprod', postgresql_using='gin')
    op.drop_index(op.f('idx_document_elements_document_id'), table_name='document_elements', schema='preprod')
    op.drop_index(op.f('idx_document_elements_hierarchy'), table_name='document_elements', schema='preprod', postgresql_using='gin')
    op.drop_index(op.f('ix_preprod_document_elements_id'), table_name='document_elements', schema='preprod')
    # op.drop_table('document_elements', schema='preprod', ondelete='CASCADE')
    op.execute('DROP TABLE IF EXISTS preprod.document_elements CASCADE')
    op.drop_index(op.f('idx_annotations_body'), table_name='annotations', schema='preprod', postgresql_using='gin')
    op.drop_index(op.f('idx_annotations_collection_id'), table_name='annotations', schema='preprod')
    op.drop_index(op.f('idx_annotations_created'), table_name='annotations', schema='preprod')
    op.drop_index(op.f('idx_annotations_creator_id'), table_name='annotations', schema='preprod')
    op.drop_index(op.f('idx_annotations_document_element_id'), table_name='annotations', schema='preprod')
    op.drop_index(op.f('idx_annotations_document_id'), table_name='annotations', schema='preprod')
    op.drop_index(op.f('idx_annotations_motivation'), table_name='annotations', schema='preprod')
    op.drop_index(op.f('idx_annotations_target'), table_name='annotations', schema='preprod', postgresql_using='gin')
    op.drop_index(op.f('idx_annotations_type'), table_name='annotations', schema='preprod')
    op.drop_index(op.f('ix_preprod_annotations_id'), table_name='annotations', schema='preprod')
    # op.drop_table('annotations', schema='preprod')
    op.execute('DROP TABLE IF EXISTS preprod.annotations CASCADE')
    op.drop_index(op.f('idx_document_elements_content'), table_name='document_elements', postgresql_using='gin')
    op.drop_index(op.f('idx_document_elements_document_id'), table_name='document_elements')
    op.drop_index(op.f('idx_document_elements_hierarchy'), table_name='document_elements', postgresql_using='gin')
    # op.drop_table('document_elements')
    op.execute('DROP TABLE IF EXISTS document_elements CASCADE')
    op.drop_index(op.f('idx_users_metadata'), table_name='users', schema='preprod', postgresql_using='gin')
    op.drop_index(op.f('ix_preprod_users_id'), table_name='users', schema='preprod')
    # op.drop_table('users', schema='preprod', ondelete='CASCADE')
    op.execute('DROP TABLE IF EXISTS preprod.users CASCADE')
    op.drop_index(op.f('idx_document_collections_created_by'), table_name='document_collections', schema='preprod')
    op.drop_index(op.f('idx_document_collections_hierarchy'), table_name='document_collections', schema='preprod', postgresql_using='gin')
    op.drop_index(op.f('idx_document_collections_metadata'), table_name='document_collections', schema='preprod', postgresql_using='gin')
    op.drop_index(op.f('idx_document_collections_modified_by'), table_name='document_collections', schema='preprod')
    op.drop_index(op.f('ix_preprod_document_collections_id'), table_name='document_collections', schema='preprod')
    # op.drop_table('document_collections', schema='preprod')
    op.execute('DROP TABLE IF EXISTS preprod.document_collections CASCADE')
    op.drop_table('alembic_version', schema='preprod')
    op.drop_index(op.f('idx_documents_collection_id'), table_name='documents')
    # op.drop_table('documents', ondelete='CASCADE')
    op.execute('DROP TABLE IF EXISTS documents CASCADE')
    op.drop_index(op.f('idx_annotations_body'), table_name='annotations', postgresql_using='gin')
    op.drop_index(op.f('idx_annotations_collection_id'), table_name='annotations')
    op.drop_index(op.f('idx_annotations_created'), table_name='annotations')
    op.drop_index(op.f('idx_annotations_creator_id'), table_name='annotations')
    op.drop_index(op.f('idx_annotations_document_element_id'), table_name='annotations')
    op.drop_index(op.f('idx_annotations_document_id'), table_name='annotations')
    op.drop_index(op.f('idx_annotations_motivation'), table_name='annotations')
    op.drop_index(op.f('idx_annotations_target'), table_name='annotations', postgresql_using='gin')
    op.drop_index(op.f('idx_annotations_type'), table_name='annotations')
    # op.drop_table('annotations')
    # op.drop_table('users')
    op.execute('DROP TABLE IF EXISTS annotations CASCADE')
    op.execute('DROP TABLE IF EXISTS users CASCADE')
    op.drop_index(op.f('idx_document_collections_created_by'), table_name='document_collections')
    op.drop_index(op.f('idx_document_collections_hierarchy'), table_name='document_collections', postgresql_using='gin')
    op.drop_index(op.f('idx_document_collections_modified_by'), table_name='document_collections')
    # op.drop_table('document_collections', ondelete='CASCADE')
    op.execute('DROP TABLE IF EXISTS document_collections CASCADE')
    op.execute("DROP EXTENSION postgis")
    op.drop_index(op.f('idx_documents_collection_id'), table_name='documents', schema='preprod')
    op.drop_index(op.f('ix_preprod_documents_id'), table_name='documents', schema='preprod')
    # op.drop_table('documents', schema='preprod', ondelete='CASCADE')
    op.execute('DROP TABLE IF EXISTS preprod.documents CASCADE')
    op.create_index('idx_document_collections_hierarchy', 'document_collections', ['hierarchy'], unique=False, schema='app', postgresql_using='gin')
    op.drop_index(op.f('idx_element_links'), table_name='document_elements', schema='app', postgresql_using='gin')
    op.drop_column('document_elements', 'links', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_elements', sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='app')
    op.create_index(op.f('idx_element_links'), 'document_elements', ['links'], unique=False, schema='app', postgresql_using='gin')
    op.drop_index('idx_document_collections_hierarchy', table_name='document_collections', schema='app', postgresql_using='gin')
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('preprod.documents_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('document_collection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_collection_id'], ['preprod.document_collections.id'], name='documents_document_collection_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='documents_pkey'),
    schema='preprod',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_preprod_documents_id'), 'documents', ['id'], unique=False, schema='preprod')
    op.create_index(op.f('idx_documents_collection_id'), 'documents', ['document_collection_id'], unique=False, schema='preprod')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey')),
    schema='app'
    )
    op.create_table('document_collections',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('document_collections_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('visibility', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('text_direction', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modified_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('hierarchy', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('collection_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='document_collections_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], name='document_collections_modified_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_collections_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_document_collections_modified_by'), 'document_collections', ['modified_by_id'], unique=False)
    op.create_index(op.f('idx_document_collections_hierarchy'), 'document_collections', ['hierarchy'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_document_collections_created_by'), 'document_collections', ['created_by_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('annotations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_collection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('document_element_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('generator', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('generated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('motivation', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('target', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('annotation_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('context', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('annotations_creator_id_fkey')),
    sa.ForeignKeyConstraint(['document_collection_id'], ['document_collections.id'], name=op.f('annotations_document_collection_id_fkey')),
    sa.ForeignKeyConstraint(['document_element_id'], ['document_elements.id'], name=op.f('annotations_document_element_id_fkey')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('annotations_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('annotations_pkey'))
    )
    op.create_index(op.f('idx_annotations_type'), 'annotations', ['type'], unique=False)
    op.create_index(op.f('idx_annotations_target'), 'annotations', ['target'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_annotations_motivation'), 'annotations', ['motivation'], unique=False)
    op.create_index(op.f('idx_annotations_document_id'), 'annotations', ['document_id'], unique=False)
    op.create_index(op.f('idx_annotations_document_element_id'), 'annotations', ['document_element_id'], unique=False)
    op.create_index(op.f('idx_annotations_creator_id'), 'annotations', ['creator_id'], unique=False)
    op.create_index(op.f('idx_annotations_created'), 'annotations', ['created'], unique=False)
    op.create_index(op.f('idx_annotations_collection_id'), 'annotations', ['document_collection_id'], unique=False)
    op.create_index(op.f('idx_annotations_body'), 'annotations', ['body'], unique=False, postgresql_using='gin')
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('documents_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('document_collection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_collection_id'], ['document_collections.id'], name='documents_document_collection_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='documents_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_documents_collection_id'), 'documents', ['document_collection_id'], unique=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='preprod'
    )
    op.create_table('document_collections',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('preprod.document_collections_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('visibility', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('text_direction', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modified_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('hierarchy', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('collection_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['preprod.users.id'], name='document_collections_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['modified_by_id'], ['preprod.users.id'], name='document_collections_modified_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_collections_pkey'),
    schema='preprod',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_preprod_document_collections_id'), 'document_collections', ['id'], unique=False, schema='preprod')
    op.create_index(op.f('idx_document_collections_modified_by'), 'document_collections', ['modified_by_id'], unique=False, schema='preprod')
    op.create_index(op.f('idx_document_collections_metadata'), 'document_collections', ['collection_metadata'], unique=False, schema='preprod', postgresql_using='gin')
    op.create_index(op.f('idx_document_collections_hierarchy'), 'document_collections', ['hierarchy'], unique=False, schema='preprod', postgresql_using='gin')
    op.create_index(op.f('idx_document_collections_created_by'), 'document_collections', ['created_by_id'], unique=False, schema='preprod')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('preprod.users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    schema='preprod',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_preprod_users_id'), 'users', ['id'], unique=False, schema='preprod')
    op.create_index(op.f('idx_users_metadata'), 'users', ['user_metadata'], unique=False, schema='preprod', postgresql_using='gin')
    op.create_table('document_elements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('hierarchy', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_elements_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_elements_pkey'))
    )
    op.create_index(op.f('idx_document_elements_hierarchy'), 'document_elements', ['hierarchy'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_document_elements_document_id'), 'document_elements', ['document_id'], unique=False)
    op.create_index(op.f('idx_document_elements_content'), 'document_elements', ['content'], unique=False, postgresql_using='gin')
    op.create_table('annotations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_collection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('document_element_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('generator', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('generated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('motivation', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('target', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('annotation_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('context', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['preprod.users.id'], name=op.f('annotations_creator_id_fkey')),
    sa.ForeignKeyConstraint(['document_collection_id'], ['preprod.document_collections.id'], name=op.f('annotations_document_collection_id_fkey')),
    sa.ForeignKeyConstraint(['document_element_id'], ['preprod.document_elements.id'], name=op.f('annotations_document_element_id_fkey')),
    sa.ForeignKeyConstraint(['document_id'], ['preprod.documents.id'], name=op.f('annotations_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('annotations_pkey')),
    schema='preprod'
    )
    op.create_index(op.f('ix_preprod_annotations_id'), 'annotations', ['id'], unique=False, schema='preprod')
    op.create_index(op.f('idx_annotations_type'), 'annotations', ['type'], unique=False, schema='preprod')
    op.create_index(op.f('idx_annotations_target'), 'annotations', ['target'], unique=False, schema='preprod', postgresql_using='gin')
    op.create_index(op.f('idx_annotations_motivation'), 'annotations', ['motivation'], unique=False, schema='preprod')
    op.create_index(op.f('idx_annotations_document_id'), 'annotations', ['document_id'], unique=False, schema='preprod')
    op.create_index(op.f('idx_annotations_document_element_id'), 'annotations', ['document_element_id'], unique=False, schema='preprod')
    op.create_index(op.f('idx_annotations_creator_id'), 'annotations', ['creator_id'], unique=False, schema='preprod')
    op.create_index(op.f('idx_annotations_created'), 'annotations', ['created'], unique=False, schema='preprod')
    op.create_index(op.f('idx_annotations_collection_id'), 'annotations', ['document_collection_id'], unique=False, schema='preprod')
    op.create_index(op.f('idx_annotations_body'), 'annotations', ['body'], unique=False, schema='preprod', postgresql_using='gin')
    op.create_table('document_elements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('hierarchy', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['preprod.documents.id'], name=op.f('document_elements_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_elements_pkey')),
    schema='preprod'
    )
    op.create_index(op.f('ix_preprod_document_elements_id'), 'document_elements', ['id'], unique=False, schema='preprod')
    op.create_index(op.f('idx_document_elements_hierarchy'), 'document_elements', ['hierarchy'], unique=False, schema='preprod', postgresql_using='gin')
    op.create_index(op.f('idx_document_elements_document_id'), 'document_elements', ['document_id'], unique=False, schema='preprod')
    op.create_index(op.f('idx_document_elements_content'), 'document_elements', ['content'], unique=False, schema='preprod', postgresql_using='gin')
    # ### end Alembic commands ###
