"""Replace site_logo_url with site_logo_enabled

Revision ID: cb6b6e159fb6
Revises: 32f74ccf98cd
Create Date: 2025-08-25 14:29:45.583564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb6b6e159fb6'
down_revision: Union[str, None] = '32f74ccf98cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_user_passwords_user_id'), table_name='user_passwords', schema='app')
    op.drop_index(op.f('ix_app_user_passwords_id'), table_name='user_passwords', schema='app')
    op.drop_table('user_passwords', schema='app')
    op.drop_column('users', 'is_active', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True), schema='app')
    op.create_table('user_passwords',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], name=op.f('user_passwords_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_passwords_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_passwords_user_id_key')),
    schema='app'
    )
    op.create_index(op.f('ix_app_user_passwords_id'), 'user_passwords', ['id'], unique=False, schema='app')
    op.create_index(op.f('idx_user_passwords_user_id'), 'user_passwords', ['user_id'], unique=False, schema='app')
    # ### end Alembic commands ###
