"""roles and permissions

Revision ID: b23f8ece0f36
Revises: c2e2ba380e53
Create Date: 2025-06-03 12:14:14.919816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23f8ece0f36'
down_revision: Union[str, None] = 'c2e2ba380e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='app'
    )
    op.create_index(op.f('ix_app_permissions_id'), 'permissions', ['id'], unique=False, schema='app')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='app'
    )
    op.create_index(op.f('ix_app_roles_id'), 'roles', ['id'], unique=False, schema='app')
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_groups_id'), 'groups', ['id'], unique=False, schema='app')
    op.create_table('object_sharing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('shared_with_id', sa.Integer(), nullable=True),
    sa.Column('shared_with_type', sa.String(length=10), nullable=True),
    sa.Column('access_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_object_sharing_object', 'object_sharing', ['object_id', 'object_type'], unique=False, schema='app')
    op.create_index('idx_object_sharing_shared_with', 'object_sharing', ['shared_with_id', 'shared_with_type'], unique=False, schema='app')
    op.create_index(op.f('ix_app_object_sharing_id'), 'object_sharing', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_object_sharing_object_id'), 'object_sharing', ['object_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_object_sharing_object_type'), 'object_sharing', ['object_type'], unique=False, schema='app')
    op.create_index(op.f('ix_app_object_sharing_shared_with_id'), 'object_sharing', ['shared_with_id'], unique=False, schema='app')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['app.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['app.roles.id'], ),
    schema='app'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['app.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    schema='app'
    )
    op.create_table('group_members',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['app.groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    schema='app'
    )
    op.add_column('annotations', sa.Column('owner_id', sa.Integer(), nullable=True), schema='app')
    op.create_index('idx_annotations_owner_id', 'annotations', ['owner_id'], unique=False, schema='app')
    op.create_foreign_key(None, 'annotations', 'users', ['owner_id'], ['id'], source_schema='app', referent_schema='app')
    op.add_column('document_collections', sa.Column('owner_id', sa.Integer(), nullable=True), schema='app')
    op.create_index('idx_document_collections_owner', 'document_collections', ['owner_id'], unique=False, schema='app')
    op.create_foreign_key(None, 'document_collections', 'users', ['owner_id'], ['id'], source_schema='app', referent_schema='app')
    op.add_column('documents', sa.Column('owner_id', sa.Integer(), nullable=True), schema='app')
    op.create_index('idx_documents_owner', 'documents', ['owner_id'], unique=False, schema='app')
    op.create_foreign_key(None, 'documents', 'users', ['owner_id'], ['id'], source_schema='app', referent_schema='app')
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True), schema='app')
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True), schema='app')
    op.create_index(op.f('ix_app_users_email'), 'users', ['email'], unique=True, schema='app')
    op.create_index(op.f('ix_app_users_username'), 'users', ['username'], unique=True, schema='app')

        # Populate default roles and permissions
    from sqlalchemy.sql import table, column
    
    # Define table references for data insertion
    roles_table = table('roles',
        column('name', sa.String),
        column('description', sa.String),
        schema='app'
    )
    
    permissions_table = table('permissions',
        column('name', sa.String),
        column('description', sa.String),
        schema='app'
    )
    
    role_permissions_table = table('role_permissions',
        column('role_id', sa.Integer),
        column('permission_id', sa.Integer),
        schema='app'
    )
    
    # Insert permissions
    permissions_data = [
        {'name': 'create_document_collection', 'description': 'Create document collections'},
        {'name': 'create_document', 'description': 'Create documents'},
        {'name': 'create_document_element', 'description': 'Create document elements'},
        {'name': 'create_scholarly_annotation', 'description': 'Create scholarly annotations'},
        {'name': 'create_commenting_annotation', 'description': 'Create commenting annotations'},
        {'name': 'comment_on_scholarly_annotation', 'description': 'Comment on scholarly annotations'},
        {'name': 'comment_on_commenting_annotation', 'description': 'Comment on commenting annotations'},
        {'name': 'access_admin_dashboard', 'description': 'Access administrative dashboard'},
        {'name': 'manage_users', 'description': 'Manage user accounts'},
        {'name': 'manage_roles', 'description': 'Assign and remove user roles'},
        {'name': 'edit_any_content', 'description': 'Edit any content in the system'},
        {'name': 'delete_any_content', 'description': 'Delete any content in the system'},
        {'name': 'view_all_content', 'description': 'View all content for oversight'},
        {'name': 'create_group', 'description': 'Create groups/classrooms'},
    ]
    
    op.bulk_insert(permissions_table, permissions_data)
    
    # Insert roles
    roles_data = [
        {'name': 'admin', 'description': 'Full system administrator'},
        {'name': 'verified_scholar', 'description': 'Verified scholar with scholarly annotation privileges'},
        {'name': 'general_user', 'description': 'General user with basic annotation capabilities'},
    ]
    
    op.bulk_insert(roles_table, roles_data)
    
    # Get connection to fetch IDs for role-permission mappings
    connection = op.get_bind()
    
    # Fetch role IDs
    admin_role_id = connection.execute(
        sa.text("SELECT id FROM app.roles WHERE name = 'admin'")
    ).fetchone()[0]
    
    scholar_role_id = connection.execute(
        sa.text("SELECT id FROM app.roles WHERE name = 'verified_scholar'")
    ).fetchone()[0]
    
    user_role_id = connection.execute(
        sa.text("SELECT id FROM app.roles WHERE name = 'general_user'")
    ).fetchone()[0]
    
    # Fetch permission IDs
    perm_ids = {}
    for perm in permissions_data:
        result = connection.execute(
            sa.text(f"SELECT id FROM app.permissions WHERE name = '{perm['name']}'")
        ).fetchone()
        perm_ids[perm['name']] = result[0]
    
    # Create role-permission mappings
    role_permission_mappings = []
    
    # Admin gets all permissions
    for perm_id in perm_ids.values():
        role_permission_mappings.append({'role_id': admin_role_id, 'permission_id': perm_id})
    
    # Verified Scholar permissions
    scholar_permissions = [
        'create_scholarly_annotation',
        'create_commenting_annotation', 
        'comment_on_scholarly_annotation',
        'comment_on_commenting_annotation'
    ]
    for perm_name in scholar_permissions:
        role_permission_mappings.append({
            'role_id': scholar_role_id, 
            'permission_id': perm_ids[perm_name]
        })
    
    # General User permissions
    user_permissions = [
        'create_commenting_annotation',
        'comment_on_commenting_annotation'
    ]
    for perm_name in user_permissions:
        role_permission_mappings.append({
            'role_id': user_role_id, 
            'permission_id': perm_ids[perm_name]
        })
    
    op.bulk_insert(role_permissions_table, role_permission_mappings)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Clean up role-permission data first (before dropping tables)
    op.execute("DELETE FROM app.role_permissions")
    op.execute("DELETE FROM app.user_roles")
    op.execute("DELETE FROM app.permissions") 
    op.execute("DELETE FROM app.roles")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_users_username'), table_name='users', schema='app')
    op.drop_index(op.f('ix_app_users_email'), table_name='users', schema='app')
    op.drop_column('users', 'username', schema='app')
    op.drop_column('users', 'email', schema='app')
    op.drop_constraint(None, 'documents', schema='app', type_='foreignkey')
    op.drop_index('idx_documents_owner', table_name='documents', schema='app')
    op.drop_column('documents', 'owner_id', schema='app')
    op.drop_constraint(None, 'document_collections', schema='app', type_='foreignkey')
    op.drop_index('idx_document_collections_owner', table_name='document_collections', schema='app')
    op.drop_column('document_collections', 'owner_id', schema='app')
    op.drop_constraint(None, 'annotations', schema='app', type_='foreignkey')
    op.drop_index('idx_annotations_owner_id', table_name='annotations', schema='app')
    op.drop_column('annotations', 'owner_id', schema='app')
    op.drop_table('group_members', schema='app')
    op.drop_table('user_roles', schema='app')
    op.drop_table('role_permissions', schema='app')
    op.drop_index(op.f('ix_app_object_sharing_shared_with_id'), table_name='object_sharing', schema='app')
    op.drop_index(op.f('ix_app_object_sharing_object_type'), table_name='object_sharing', schema='app')
    op.drop_index(op.f('ix_app_object_sharing_object_id'), table_name='object_sharing', schema='app')
    op.drop_index(op.f('ix_app_object_sharing_id'), table_name='object_sharing', schema='app')
    op.drop_index('idx_object_sharing_shared_with', table_name='object_sharing', schema='app')
    op.drop_index('idx_object_sharing_object', table_name='object_sharing', schema='app')
    op.drop_table('object_sharing', schema='app')
    op.drop_index(op.f('ix_app_groups_id'), table_name='groups', schema='app')
    op.drop_table('groups', schema='app')
    op.drop_index(op.f('ix_app_roles_id'), table_name='roles', schema='app')
    op.drop_table('roles', schema='app')
    op.drop_index(op.f('ix_app_permissions_id'), table_name='permissions', schema='app')
    op.drop_table('permissions', schema='app')
    # ### end Alembic commands ###
