"""generic login

Revision ID: 32f74ccf98cd
Revises: c041068b67c3
Create Date: 2025-08-22 14:11:14.286321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32f74ccf98cd'
down_revision: Union[str, None] = 'c041068b67c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='app'
    )
    op.create_index('idx_user_passwords_user_id', 'user_passwords', ['user_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_user_passwords_id'), 'user_passwords', ['id'], unique=False, schema='app')
    op.drop_index(op.f('idx_site_settings_updated_by'), table_name='site_settings', schema='app')
    op.drop_table('site_settings', schema='app')
    op.drop_table('alembic_version')
    op.drop_index(op.f('ix_app_invitations_email'), table_name='invitations', schema='app')
    op.drop_index(op.f('ix_app_invitations_id'), table_name='invitations', schema='app')
    op.drop_index(op.f('ix_app_invitations_invitation_token'), table_name='invitations', schema='app')
    op.drop_table('invitations', schema='app')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'),
               schema='app')
    op.drop_index(op.f('ix_users_is_active'), table_name='users', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False, schema='app')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               schema='app')
    op.create_table('invitations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('invitation_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['app.users.id'], name=op.f('invitations_created_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('invitations_pkey')),
    schema='app'
    )
    op.create_index(op.f('ix_app_invitations_invitation_token'), 'invitations', ['invitation_token'], unique=True, schema='app')
    op.create_index(op.f('ix_app_invitations_id'), 'invitations', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_invitations_email'), 'invitations', ['email'], unique=False, schema='app')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('site_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('site_title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('site_logo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['app.users.id'], name=op.f('site_settings_updated_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('site_settings_pkey')),
    schema='app'
    )
    op.create_index(op.f('idx_site_settings_updated_by'), 'site_settings', ['updated_by_id'], unique=False, schema='app')
    op.drop_index(op.f('ix_app_user_passwords_id'), table_name='user_passwords', schema='app')
    op.drop_index('idx_user_passwords_user_id', table_name='user_passwords', schema='app')
    op.drop_table('user_passwords', schema='app')
    # ### end Alembic commands ###
