"""collection_metadata

Revision ID: 4864abeefa46
Revises: 5701ab183d99
Create Date: 2026-01-19 16:41:26.480556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4864abeefa46'
down_revision: Union[str, None] = '5701ab183d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'site_settings',
        sa.Column(
            'collection_metadata_schema',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            server_default=sa.text("'[]'::jsonb")
        ),
        schema='app'
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'collection_metadata_schema', schema='app')
    # ### end Alembic commands ###
