"""add sort order

Revision ID: 2088c7ea8d55
Revises: 4864abeefa46
Create Date: 2026-01-29 20:30:11.636859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2088c7ea8d55'
down_revision: Union[str, None] = '4864abeefa46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add display_order column to document_collections
    op.add_column('document_collections', sa.Column('display_order', sa.Integer(), nullable=True), schema='app')
    # Populate existing rows with order based on creation date (oldest first)
    op.execute("""
        UPDATE app.document_collections
        SET display_order = subquery.row_num
        FROM (
            SELECT id, ROW_NUMBER() OVER (ORDER BY created ASC) as row_num
            FROM app.document_collections
        ) AS subquery
        WHERE document_collections.id = subquery.id
            AND document_collections.display_order IS NULL
    """)
    # Make column non-nullable and set default
    op.alter_column('document_collections', 'display_order', nullable=False, server_default='0', schema='app')
    # Create index for faster ordering
    op.create_index('idx_document_collections_display_order', 'document_collections', ['display_order'], schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop index for display_order
    op.drop_index('idx_document_collections_display_order', table_name='document_collections', schema='app')
    # Drop display_order column
    op.drop_column('document_collections', 'display_order', schema='app')
    # ### end Alembic commands ###
