FROM python:3.10-slim

RUN apt update -qq && apt upgrade -y

WORKDIR /app

# Install dependencies first (for better caching)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
# COPY alembic.ini .
# COPY alembic/ ./alembic/


ENV ALEMBIC_CONFIG=/app/alembic.ini

# Set the entrypoint to alembic
ENTRYPOINT ["alembic"]
# Default command (can be overridden)
CMD ["upgrade", "head"]
